name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade U pip
          python -m pip install flit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Publish to PyPI
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m flit publish
